### ISSUE TITLE
Nav bar is hidding content when accessing anchor

### ISSUE THREAD

**Issue by germinolegrand** [manicatorman/thebreadbook.org#12]
When you click on a link in the summary for exemple, or a footnote, you end up scrolling too much because the anchors is positionned under the fixed top bar.
This is due to a booststrap bug... https://github.com/twbs/bootstrap/issues/1768 quite boresome...

A quick fix that works as far as i've seen :
`
*[id]:before { 
  display: block; 
  content: " "; 
  margin-top: -100px;
  height: 100px;
  visibility: hidden; 
}
`

**Comment by manicatorman** [comment]
I just updated the site - I don't think this is still an issue. Thanks for the heads up.
