### ISSUE TITLE
Missing Anarchist FAQ Image

### ISSUE THREAD

**Issue by bitmold** [manicatorman/thebreadbook.org#19]
At http://thebreadbook.org/resources.html the[Anarchist FAQ ](http://anarchism.pageabode.com/afaq/index.html) is missing an image (it's looking for `images/afaq.jpg`). After looking at the images directory, it does not seem like any of the images are directly associated with the Anarchist FAQ. 

We should probably just grab one from the FAQ's website

**Comment by manicatorman** [comment]
Thanks for this! After updating the site, the anarchist FAQ link has been removed entirely, so this issue has been resolved.
