### ISSUE TITLE
Transfer ownership?

### ISSUE THREAD

**Issue by nteiv** [manicatorman/thebreadbook.org#24]
Hi, manicatorman. I just noticed you updated the SSL cert and I had thought you'd abandoned the project. I have cloned and worked on the source code of the website for a couple of weeks now at : 
https://github.com/breadbook/thebreadbook.org/

If you wouldn't mind, I feel like I might do a better job at maintaining the website with my programming and systems administration knowledge.

I also see that the domain expires on the 5th but I'm not sure if you have it set-up on auto-renew? 

If you'd like to reach me by email: thebreadbook@protonmail.com

**Comment by manicatorman** [comment]
Hi @nteiv! Thanks for reaching out! This is wild, I was absolutely thinking of transferring ownership really soon anyway! I've been extremely offline lately, so I haven't been able to work on the website or do anything with it. And hosting has gotten a bit too expensive for me. I will absolutely email you!

**Comment by manicatorman** [comment]
@nteiv Hey, I opened an issue on your breadbook repository - it still isn't working when you add the "www" to the start of the address. Let me know if there is something I need to do to get that working!
