### ISSUE TITLE
Licenses Don't Match

### ISSUE THREAD

**Issue by bitmold** [manicatorman/thebreadbook.org#8]
The repository contains a GNU General Public License v3.0 but the footer on the site reads

> Everything is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License, except for The Conquest of Bread, which is in the public domain.

Should the site reflect the license in the repository? Or vice versa? I'm not sure

**Comment by manicatorman** [comment]
I actually think the code can be licensed under the GPL, and the creative content licensed under the CCA with no conflict. The footer on the site is referring to the creative content, like the posters and writing, not the source code.
